# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla-onessd

---
# configuration for scylla
apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
  namespace: scylla-onessd
data:
  scylla.yaml: |
    auto_snapshot: false
    commitlog_total_space_in_mb: 10000
---

# Role for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onessd-member
  namespace: scylla-onessd
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - scylla.scylladb.com
    resources:
      - scyllaclusters
    verbs:
      - get

---

# ServiceAccount for scylla members.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onessd-member
  namespace: scylla-onessd

---

# RoleBinding for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: onessd-member
  namespace: scylla-onessd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: onessd-member
subjects:
  - kind: ServiceAccount
    name: onessd-member
    namespace: scylla-onessd

---

# Scylla Cluster
apiVersion: scylla.scylladb.com/v1alpha1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: onessd 
  namespace: scylla-onessd
spec:
  version: 4.2.0
  agentVersion: 2.2.0
  cpuset: true
  sysctls:
    - "fs.aio-max-nr=2097152"
  network:
    hostNetworking: true
  datacenter:
    name: us-east4-a
    racks:
      - name: us-east4
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 3
        storage:
          storageClassName: "local-raid-disks"
          capacity: 100G
        resources:
          limits:
            cpu: 14
            memory: 40G
          requests:
            cpu: 14
            memory: 40G
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east4-a
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters-onessd
              effect: NoSchedule
