# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: skinny-scylla

---

# Role for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: benchmark-member
  namespace: skinny-scylla
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - scylla.scylladb.com
    resources:
      - scyllaclusters
    verbs:
      - get

---

# ServiceAccount for scylla members.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmark-member
  namespace: skinny-scylla

---

# RoleBinding for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: benchmark-member
  namespace: skinny-scylla
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: benchmark-member
subjects:
  - kind: ServiceAccount
    name: benchmark-member
    namespace: skinny-scylla

---

# Scylla Cluster
apiVersion: scylla.scylladb.com/v1alpha1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: benchmark
  namespace: skinny-scylla
spec:
  version: 4.2.0
  agentVersion: 2.2.0
  cpuset: true
  sysctls:
    - "fs.aio-max-nr=2097152"
  network:
    hostNetworking: true
  datacenter:
    name: us-east4-a
    racks:
      - name: us-east4
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 3
        storage:
          storageClassName: "ssd"
          capacity: 100G
        resources:
          limits:
            cpu: 14
            memory: 40G
          requests:
            cpu: 14
            memory: 40G
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east4-a
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters
              effect: NoSchedule
